# Generated by Django 3.2.12 on 2024-01-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finch',
        ),
    ]
