# Generated by Django 3.2.12 on 2024-01-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_delete_finch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('personality', models.TextField(max_length=150)),
                ('age_span', models.IntegerField()),
            ],
        ),
    ]
